### ISSUE TITLE
Feature request: Add support for custommodeldata

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#35]
**Is your feature request related to a problem? Please describe.**
I use a lot of custom items on my server, I would like to be able to display them and use them as lobby items.

**Describe the solution you'd like**
Example of config
```
  start:
    material: "CLOCK"
    custommodeldata: 1
    name: "&6 Start Spillet "
    lore: []
    position: 0
    enabled: true
    adminOnly: false
```

**Describe alternatives you've considered**
-

**Additional context**
-
